name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'
    steps:
    - name: Install dependencies (linux)
      run: |
        sudo apt-get update
        sudo apt-get install libgl1-mesa-dev xorg-dev 
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1024x768x16 +extension RANDR &
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - run: go version

    - name: Install dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: | 
        go test -v ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out -o=coverage.out

    - name: Go Coverage Badge  
      uses: tj-actions/coverage-badge-go@v2
      with:
        filename: coverage.out

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v12
      id: verify-changed-files
      with:
        files: README.md

    - name: Commit coverage changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "update coverage badge"

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.head_ref }}
